language: python

sudo: required
dist: trusty

python: "3.6"

services:
  - docker

before_script:
  - sudo /etc/init.d/mysql stop

script:
  - ./ci/bootstrap.sh
  - ./ci/test-data.sh
  - ./ci/test-migrations.sh

after_success:
  - docker exec -i faf-db /dump-structure.sh
  - ./ci/docker-build.sh
