language: python

sudo: required
dist: trusty

python: "3.5"

services:
  - docker

before_script:
  - sudo /etc/init.d/mysql stop

script:
  - chmod +x ./test.sh && ./test.sh
  - docker exec -i faf-db mysql -uroot -pbanana faf < test-data.sql
  - chmod +x ./test-migrations.sh && ./test-migrations.sh

after_success:
  - docker exec -i faf-db /dump-structure.sh
  - if [ -n "${TRAVIS_TAG}" ]; then
      docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}";
      docker push faforever/faf-db;
    fi

after_failure:
  - docker logs faf-db
