language: python

sudo: required
dist: trusty

python: "3.5"

services:
  - docker

before_script:
  - sudo /etc/init.d/mysql stop

script:
  - chmod +x ./test.sh && ./test.sh

after_success:
  - docker exec -i faf-db /dump-structure.sh

after_failure:
  - docker logs faf-db
