sudo: required

services:
  - docker

before_script:
  - sudo /etc/init.d/mysql stop

script:
  - ./ci/bootstrap.sh
  - ./ci/test-data.sh
  - ./ci/test-migrations.sh

after_success:
  - ./ci/schemaspy.sh
  - ./ci/docker-build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAGES_TOKEN
  keep_history: false
  on:
    branch: develop
  local_dir: ./public